# Generated by Django 5.1.3 on 2024-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_of_tour', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('remaining_capacity', models.PositiveIntegerField()),
                ('transportation_type', models.CharField(choices=[('اتوبوس', 'اتوبوس'), ('قطار', 'قطار'), ('هواپیما', 'هواپیما')], max_length=10)),
                ('price', models.IntegerField()),
                ('price_off', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='tour_photos/')),
            ],
        ),
    ]
