# Generated by Django 5.1.3 on 2024-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_tour_transportation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='transportation_type',
            field=models.CharField(choices=[('اتوبوس', 'اتوبوس'), ('قطار', 'قطار'), ('پرواز داخلی', 'پرواز داخلی'), ('پرواز خارجی', 'پرواز خارجی')], max_length=20),
        ),
    ]
